In [ ]:
pip install ultralytics

# Download the cutlery dataset

In [ ]:
#!unzip /content/cutlery_31okt2023.zip

# Train the model

In [ ]:
from ultralytics import YOLO
# Load a model
model = YOLO('yolov8n.pt')  # build from YAML and transfer weights



In [ ]:
#model = YOLO('/content/runs/detect/train8/weights/last.pt') #Resume training bc validation loss still decreasing --> resume=True
# Use the model
model.train(data="/content/cutlery_31okt2023/data.yaml", epochs=100, patience=20, freeze=22, batch=128, imgsz=(480, 640))  # train the model



Ultralytics YOLOv8.0.206 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=/content/runs/detect/train8/weights/last.pt, data=/content/cutlery_31okt2023/data.yaml, epochs=100, patience=20, batch=128, imgsz=(480, 640), save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train83, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=22, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=Fals

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2, 3, 4, 5])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7c9530295ba0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
     

In [ ]:
metrics = model.val()  # evaluate model performance on the validation set

Ultralytics YOLOv8.0.206 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Model summary (fused): 168 layers, 3006818 parameters, 0 gradients, 8.1 GFLOPs
val: Scanning /content/cutlery_31okt2023/valid/labels.cache... 48 images, 0 backgrounds, 0 corrupt: 100%|██████████| 48/48 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.44s/it]
                   all         48         81      0.755      0.845      0.823      0.645
                  bowl         48          9      0.917          1      0.995      0.891
                   cup         48         18      0.953          1      0.995       0.77
                  fork         48         14      0.363        0.5      0.466      0.302
                 knife         48         14      0.536      0.786      0.599       0.42
                 plate         48         12      0.977          1      0.995      0.834
                 spoon 

# Evaluate training

In [ ]:
import os
from PIL import Image

test_directory = "/content/cutlery_31okt2023/test/images/"
results_directory = "/content/results/"

if not os.path.exists(results_directory):
    os.makedirs(results_directory)

test_images = os.listdir(test_directory)


for image_filename in test_images:
    image_path = os.path.join(test_directory, image_filename)

    results = model(image_path)

    # Show and save the results
    for idx, r in enumerate(results):
        print(r.boxes.conf)
        print(r.boxes.cls)
        im_array = r.plot()  # plot a BGR numpy array of predictions
        im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
        result_filename = f"{os.path.splitext(image_filename)[0]}_result_{idx}.jpg"
        result_path = os.path.join(results_directory, result_filename)
        im.save(result_path)  # save image


image 1/1 /content/cutlery_31okt2023/test/images/frame0222_jpg.rf.082d5fc2be49b91b3f7a8d6d09f20e5f.jpg: 480x640 1 fork, 1 knife, 7.8ms
Speed: 1.4ms preprocess, 7.8ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0131_jpg.rf.f97c48c68857abbd71b9311eb687bd63.jpg: 480x640 1 cup, 9.3ms
Speed: 1.4ms preprocess, 9.3ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0077_jpg.rf.a00fcf9b188ef5576820a79536913a86.jpg: 480x640 1 bowl, 7.2ms
Speed: 1.1ms preprocess, 7.2ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0178_jpg.rf.ed03b54a3ce2bb3b0ff74f900e7cfb6e.jpg: 480x640 1 spoon, 7.1ms
Speed: 1.1ms preprocess, 7.1ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0023_jpg.rf.7276f5c21a5ebf63ed71c68c3889e21e

tensor([0.4711, 0.4440], device='cuda:0')
tensor([2., 3.], device='cuda:0')
tensor([0.9215], device='cuda:0')
tensor([1.], device='cuda:0')
tensor([0.9318], device='cuda:0')
tensor([0.], device='cuda:0')
tensor([0.3051], device='cuda:0')
tensor([5.], device='cuda:0')
tensor([0.6813, 0.5285, 0.5219, 0.5212, 0.3863, 0.2623, 0.2546], device='cuda:0')
tensor([2., 3., 3., 2., 2., 1., 2.], device='cuda:0')
tensor([0.9148], device='cuda:0')
tensor([4.], device='cuda:0')



image 1/1 /content/cutlery_31okt2023/test/images/frame0160_jpg.rf.8c0ffcf8655931678c59ae71887a19f8.jpg: 480x640 1 plate, 7.5ms
Speed: 1.1ms preprocess, 7.5ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0039_jpg.rf.7e4b810856db88589edd03aada5eb99c.jpg: 480x640 1 bowl, 8.0ms
Speed: 1.3ms preprocess, 8.0ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0013_jpg.rf.4ea699716952a15c8f35766766ff6936.jpg: 480x640 1 plate, 7.9ms
Speed: 1.0ms preprocess, 7.9ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0102_jpg.rf.e50023ff53b12ec1375a8778b9cbc589.jpg: 480x640 1 fork, 2 knifes, 2 spoons, 10.1ms
Speed: 1.6ms preprocess, 10.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0196_jpg.rf.0caef0cba9026eab3

tensor([0.6691], device='cuda:0')
tensor([4.], device='cuda:0')
tensor([0.9429], device='cuda:0')
tensor([4.], device='cuda:0')
tensor([0.9214], device='cuda:0')
tensor([0.], device='cuda:0')
tensor([0.6056], device='cuda:0')
tensor([4.], device='cuda:0')
tensor([0.9309, 0.9119, 0.7845, 0.5343, 0.3199], device='cuda:0')
tensor([3., 5., 3., 5., 2.], device='cuda:0')
tensor([0.8876], device='cuda:0')
tensor([0.], device='cuda:0')


image 1/1 /content/cutlery_31okt2023/test/images/frame0073_jpg.rf.8012cfe0c727a9f1925a96b7e539b053.jpg: 480x640 1 bowl, 12.4ms
Speed: 1.2ms preprocess, 12.4ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0179_jpg.rf.32aaec3eb6efc50a4ca746acadb62691.jpg: 480x640 1 knife, 1 spoon, 7.8ms
Speed: 1.1ms preprocess, 7.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0021_jpg.rf.2943ca7661a947b5286b337fff9f1272.jpg: 480x640 1 cup, 7.5ms
Speed: 1.1ms preprocess, 7.5ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0055_jpg.rf.37053abf7ae22e2379df8ff6107161f2.jpg: 480x640 1 cup, 8.6ms
Speed: 1.2ms preprocess, 8.6ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/left0007_jpg.rf.f3c59cbde4d9e9a3ca8290a73c788200.

tensor([0.9544], device='cuda:0')
tensor([0.], device='cuda:0')
tensor([0.3960, 0.2897], device='cuda:0')
tensor([3., 5.], device='cuda:0')
tensor([0.9578], device='cuda:0')
tensor([1.], device='cuda:0')
tensor([0.9824], device='cuda:0')
tensor([1.], device='cuda:0')
tensor([0.9490], device='cuda:0')
tensor([0.], device='cuda:0')
tensor([0.5723, 0.4676, 0.3474], device='cuda:0')
tensor([3., 5., 2.], device='cuda:0')


image 1/1 /content/cutlery_31okt2023/test/images/frame0210_jpg.rf.01e9e7a7543923fcd795556c64b96fbb.jpg: 480x640 1 cup, 8.0ms
Speed: 1.1ms preprocess, 8.0ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0103_jpg.rf.22cc52d3e468b2fba86456d639c7387d.jpg: 480x640 1 fork, 3 knifes, 1 spoon, 8.4ms
Speed: 1.1ms preprocess, 8.4ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0083_jpg.rf.b7bcf9a335d3fbfb1812b69957a9542c.jpg: 480x640 1 plate, 8.0ms
Speed: 1.1ms preprocess, 8.0ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0201_jpg.rf.c6410d3034f4e57aa7b64ae48bfe64e5.jpg: 480x640 1 cup, 1 plate, 9.9ms
Speed: 1.1ms preprocess, 9.9ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /content/cutlery_31okt2023/test/images/frame0088_jpg.rf.d732c71680278b2

tensor([0.8813], device='cuda:0')
tensor([1.], device='cuda:0')
tensor([0.8384, 0.8116, 0.6593, 0.5122, 0.3884], device='cuda:0')
tensor([3., 5., 2., 3., 3.], device='cuda:0')
tensor([0.9339], device='cuda:0')
tensor([4.], device='cuda:0')
tensor([0.8124, 0.3416], device='cuda:0')
tensor([1., 4.], device='cuda:0')
tensor([0.8522], device='cuda:0')
tensor([4.], device='cuda:0')
tensor([0.8277, 0.5196, 0.3446], device='cuda:0')
tensor([3., 5., 5.], device='cuda:0')
